<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206140304 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recently_viewed (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, hotel_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15206538A76ED395 ON recently_viewed (user_id)');
        $this->addSql('CREATE INDEX IDX_152065383243BB18 ON recently_viewed (hotel_id)');
        $this->addSql('ALTER TABLE recently_viewed ADD CONSTRAINT FK_15206538A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recently_viewed ADD CONSTRAINT FK_152065383243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recently_viewed DROP CONSTRAINT FK_15206538A76ED395');
        $this->addSql('ALTER TABLE recently_viewed DROP CONSTRAINT FK_152065383243BB18');
        $this->addSql('DROP TABLE recently_viewed');
    }
}
