<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206142105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE offer_price_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price NUMERIC(10, 2) NOT NULL, price_per_person BOOLEAN NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes TEXT DEFAULT NULL, offer_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_10C8EB1C53C674EE ON offer_price_history (offer_id)');
        $this->addSql('CREATE INDEX idx_offer_checked ON offer_price_history (offer_id, checked_at)');
        $this->addSql('ALTER TABLE offer_price_history ADD CONSTRAINT FK_10C8EB1C53C674EE FOREIGN KEY (offer_id) REFERENCES offer (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE offer_price_history DROP CONSTRAINT FK_10C8EB1C53C674EE');
        $this->addSql('DROP TABLE offer_price_history');
    }
}
